# Generated by Django 4.2.8 on 2023-12-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="S3model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_id", models.CharField(max_length=100)),
                ("access_key", models.CharField(max_length=100)),
                ("bucket_name", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TelegramApi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key1", models.CharField(max_length=300)),
                ("chat_id", models.CharField(max_length=200)),
            ],
        ),
    ]
